spring.jackson.deserialization.fail-on-unknown-properties=false

spring.task.scheduling.pool.size=2
spring.task.scheduling.shutdown.await-termination=true
spring.task.scheduling.thread-name-prefix=nethelt-task-
spring.task.scheduling.shutdown.await-termination-period=10s

spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=10
spring.task.execution.pool.queue-capacity=100
spring.task.execution.thread-name-prefix=nethelt-monitoring-
spring.task.execution.shutdown.await-termination=true