spring.jackson.deserialization.fail-on-unknown-properties=false

spring.task.scheduling.pool.size=2
spring.task.scheduling.shutdown.await-termination=true
spring.task.scheduling.thread-name-prefix=nethelt-task-
spring.task.scheduling.shutdown.await-termination-period=10s

scheduler.update-interval-seconds=60
scheduler.heartbeat-interval-seconds=60

spring.http.serviceclient.web-api.base-url=${WEB_API_BASE_URL:http://localhost:8080/api}
spring.http.serviceclient.web-api.connect-timeout=3s
spring.http.serviceclient.web-api.read-timeout=5s
spring.http.serviceclient.web-api.default-header.X-API-Version=1.0.0