spring.jackson.deserialization.fail-on-unknown-properties=false

spring.task.scheduling.pool.size=2
spring.task.scheduling.shutdown.await-termination=true
spring.task.scheduling.thread-name-prefix=nethelt-task-
spring.task.scheduling.shutdown.await-termination-period=10s