spring.application.name=nethelt-web-backend
logging.level.pl.sgorski.nethelt=DEBUG

server.forward-headers-strategy=framework
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

# Thread pool configuration
spring.threads.virtual.enabled=true
spring.task.execution.shutdown.await-termination=true
spring.task.execution.shutdown.await-termination-period=20s

# MVC configuration
spring.mvc.apiversion.default=1.0.0
server.servlet.context-path=/api
spring.mvc.apiversion.default=1
spring.mvc.apiversion.use.header=X-API-Version
spring.mvc.apiversion.detect-supported=true

# Swagger configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.persist-authorization=true

# Actuator configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=when_authorized
management.endpoint.health.probes.enabled=true

# Database configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.mode=never
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# OAuth2 configuration
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=user:email
spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# HTTP Clients configuration
github.client.read-timeout-ms=5000
github.client.connection-timeout-ms=3000
github.client.base-url=https://api.github.com

# Application variables
jwt.secret-key=${JWT_SECRET_KEY}
jwt.expiration-time-in-ms=${JWT_EXPIRATION_TIME_MS}

nh.frontend.oauth-success-url=${FRONTEND_OAUTH2_SUCCESS_URL:http://localhost:3000/oauth/success}
