services:
  nh-postgres:
    image: postgres:18.2-alpine
    container_name: nh-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - nh-postgres-data:/var/lib/postgresql/18/docker
    networks:
      - nh-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  nh-web-api:
    build:
      context: ..
      dockerfile: ./web-api/Dockerfile
    container_name: nh-web-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      nh-postgres:
        condition: service_healthy
    networks:
      - nh-network

  nh-ai-model:
    build:
      context: ../ai-model
      dockerfile: Dockerfile
    container_name: nh-ai-model
    restart: unless-stopped
    networks:
      - nh-network

  nh-frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: nh-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - nh-web-api
    networks:
      - nh-network

volumes:
  nh-postgres-data:

networks:
  nh-network:
    driver: bridge
